# build the docker image
# push the docker image to docker hub
# ssh into our vm and start the new image

name: Deploy a backend
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout the code
        uses: actions/Checkout@v2
      
      - name: Docker login
        uses: docker/login-action@v2
        with: 
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with: 
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: prathvishs/deploy_todo_monorepo_backend:${{github.sha}}
          # build-args: |
          #   DATABASE_URL=${{ secrets.DATABASE_URL }}
          # step to deploy this to a VM - k8, autoscaling group

      - name: Deploy to VM
        run: |
          echo "${{secrets.SSH_PRIVATE_KEY}}" &> ~/ssh_key
          mkdir -p /home/runner/.ssh
          ls home/runner/.ssh
          touch /home/runner/.ssh/known_hosts
          echo "${{secrets.KNOWN_HOSTS}}" &> /home/runner/.ssh/known_hosts
          chmod 700 /home/runner/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@your.vm.ip.address -t "docker stop user_backend && docker run --name user_backend -d -p 8080:8080 prathvishs/deploy_todo_monorepo_backend:${{github.sha}}"